# Default initial positions for rbs_arm's ros2_control fake system

initial_positions:
  ee_link_joint: 0
  fork0_link_joint: 0
  fork1_link_joint: 0
  fork2_link_joint: 0
  main0_link_joint: 0
  main1_link_joint: 0
  rbs_gripper_rot_base_joint: 0
