robot_description_kinematics:
  rbs_arm:
    kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
    kinematics_solver_search_resolution: 0.1
    kinematics_solver_timeout: 0.005
    kinematics_solver_attempts: 3
