moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
      - rbs_gripper_rot_base_joint
