controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController
    motion_controller_handle:
      type: cartesian_controller_handles/MotionControlHandle
    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController
    gripper_controller:
      type: position_controllers/GripperActionController
    # gripper_controller:
    #   type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
      - rbs_gripper_rot_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "gripper_grasp_point"
    robot_base_link: "base_link"
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
      - rbs_gripper_rot_base_joint
    command_interfaces:
      - position
    solver:
      error_scale: 1.0
      iterations: 10
      publish_state_feedback: True
    pd_gains:
      trans_x: { p: 100.0 }
      trans_y: { p: 100.0 }
      trans_z: { p: 100.0 }
      rot_x: { p: 50.5 }
      rot_y: { p: 50.5 }
      rot_z: { p: 50.5 }

motion_controller_handle:
  ros__parameters:
    end_effector_link: "gripper_grasp_point"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tool0"
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
      - rbs_gripper_rot_base_joint

# gripper_controller:
#   ros__parameters:
#     joints:
#       - rbs_gripper_r_finger_joint
#     interface_name: effort

joint_effort_controller:
  ros__parameters:
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
  
gripper_controller:
  ros__parameters:
    action_monitor_rate: 200.0
    joint: rbs_gripper_r_finger_joint
    goal_tolerance: 0.01
    max_effort: 5.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 2.0
    # gains:
    #   gripper_joint: { p: 200, d: 1, i: 5, i_clamp: 1 }
