controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController
    motion_controller_handle:
      type: cartesian_controller_handles/MotionControlHandle


joint_trajectory_controller:
  ros__parameters:
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint
    command_interfaces:
      - position
    solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True
    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}

motion_controller_handle:
  ros__parameters:
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tool0"
    joints:
      - fork0_link_joint
      - main0_link_joint
      - fork1_link_joint
      - main1_link_joint
      - fork2_link_joint
      - ee_link_joint

#TODO: add cartesian_compliance_controller
