rbs_arm:
  rbs_arm:
    rbs_arm:
      rbs_arm:
        rbs_arm:
          cartesian_motion_controller:
            ros__parameters:
              command_interfaces:
              - position
              end_effector_link: rbs_arm_link_tool0
              joints:
              - rbs_arm_joint_1
              - rbs_arm_joint_2
              - rbs_arm_joint_3
              - rbs_arm_joint_4
              - rbs_arm_joint_5
              - rbs_arm_joint_6
              pd_gains:
                rot_x:
                  p: 0.5
                rot_y:
                  p: 0.5
                rot_z:
                  p: 0.5
                trans_x:
                  p: 1.0
                trans_y:
                  p: 1.0
                trans_z:
                  p: 1.0
              robot_base_link: rbs_arm_link_0
              solver:
                error_scale: 1.0
                iterations: 10
                publish_state_feedback: true
          controller_manager:
            ros__parameters:
              cartesian_motion_controller:
                type: cartesian_motion_controller/CartesianMotionController
              gripper_controller:
                type: forward_command_controller/ForwardCommandController
              joint_state_broadcaster:
                type: joint_state_broadcaster/JointStateBroadcaster
              joint_trajectory_controller:
                type: joint_trajectory_controller/JointTrajectoryController
              update_rate: 1000
          gripper_controller:
            ros__parameters:
              interface_name: position
              joints:
              - rbs_arm_joint_1
              - rbs_arm_joint_2
              - rbs_arm_joint_3
              - rbs_arm_joint_4
              - rbs_arm_joint_5
              - rbs_arm_joint_6
          joint_trajectory_controller:
            ros__parameters:
              action_monitor_rate: 20.0
              allow_partial_joints_goal: false
              command_interfaces:
              - position
              joints:
              - rbs_arm_joint_1
              - rbs_arm_joint_2
              - rbs_arm_joint_3
              - rbs_arm_joint_4
              - rbs_arm_joint_5
              - rbs_arm_joint_6
              state_interfaces:
              - position
              - velocity
              state_publish_rate: 100.0
